### ISSUE TITLE
Add Radio Button & fill in w/ options

### ISSUE THREAD

**Issue by apalm112** [apalm112/YouTubeAPI#5]

**Comment by rdsannicolas** [comment]
The Radio Button should have the following:
1) Code Fellows Youtube Channel
2) HTML
3) CSS
4) Javascript
5) Python
6) Objective C
7) Swift

Or, do we combine HTML/CSS/Javascript? and Objective C and Swift? (both are for iOS development).

**Comment by rdsannicolas** [comment]
Done!
